name: damroc
dependencies:
  - python=3.6
  - numpy
  - pandas
  - pip
  - pip:
    - pybloomfiltermmap
    - losswise
    - sklearn
    - lief
    - http://download.pytorch.org/whl/torch-0.3.0.post4-cp36-cp36m-macosx_10_7_x86_64.whl
    - matplotlib